language: objective-c
os: osx
jobs:
  include:
  - osx_image: xcode11.3
    env: XCODE_VER=113
env:
  global:
    - tag=v0.0.10
script:
- travis_wait make production
before_deploy:
- export TRAVIS_TAG=$tag
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  token: $TOKEN
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true