language: objective-c
matrix:
  include:
  - osx_image: xcode11.3
    env: XCODE_VER=113
branches:
  only:
  - master
env:
  global:
    - tag=v0.0.6
before_script:
- brew tap tcnksm/ghr
- brew install ghr
script:
- travis_wait make production
after_script:
- ghr -t $TOKEN -u ppm-manish -r KnobControl -c master -b "KnobControl iOS SDK version $tag Swift support 5.1(XCode 11.3)" $tag releases/
deploy:
  provider: releases
  api_key: $TOKEN
  local_dir: releases
  skip_cleanup: true
  draft: true
