os: osx
osx_image: xcode9.3
language: objective-c
sudo: required
install:
- wget https://swift.org/builds/swift-5.2-branch/xcode/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a-osx.pkg
- sudo installer -pkg swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a-osx.pkg -target /
- export PATH="/Library/Developer/Toolchains/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a.xctoolchain/usr/bin:$PATH"
script:
- make production
deploy:
  provider: releases
  api_key: $TOKEN
  file: releases/KnobControl-iOS-0.0.6.tar.gz
  skip_cleanup: true
  on:
    tags: true
