language: objective-c
os: osx
jobs:
  include:
  - osx_image: xcode11.3
    env: XCODE_VER=113
env:
  global:
    - tag=v0.0.6
before_script:
- brew tap tcnksm/ghr
- brew install ghr
script:
- echo $TOKEN
- echo $tag
- travis_wait make production
after_script:
- echo $TOKEN
- ghr -t $TOKEN -u ppm-manish -r KnobControl -c master -b "KnobControl iOS SDK version $tag Swift support 5.1(XCode 11.3)" $tag releases/
deploy:
  provider: releases
  token: $TOKEN
  file: KnobControl-iOS-0.0.6.tar.gz
  cleanup: false
  draft: true