language: objective-c
matrix:
  include:
  - osx_image: xcode11.3
    env: XCODE_VER=113
branches:
  only:
  - master
env:
  global:
    - tag=v0.0.3
before_script:
- brew tap tcnksm/ghr
- brew install ghr
script:
- make production
after_script:
- ghr -t f4058e7508663bf25972351a9b1a02ade3625b1c -u ppm-manish -r KnobControl -c master -b $"KnobControl iOS SDK version $tag Swift support 5.1(XCode 11.3)" $tag releases/