os: osx
osx_image: xcode11.3
language: objective-c
sudo: required
install:
- wget https://swift.org/builds/swift-5.2-branch/xcode/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a-osx.pkg
- sudo installer -pkg swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a-osx.pkg -target /
- export PATH="/Library/Developer/Toolchains/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-01-13-a.xctoolchain/usr/bin:$PATH"
script:
- make production
deploy:
  provider: releases
  github_token: $TOKEN
  local_dir: releases
  skip_cleanup: true
  on:
    branch: master
