language: objective-c
os: osx
jobs:
  include:
  - osx_image: xcode11.3
    env: XCODE_VER=113
env:
  global:
    - tag=v0.0.6
before_script:
- brew tap tcnksm/ghr
- brew install ghr
script:
- echo $TOKEN
- echo $SECURE_TOKEN
- echo $TARGET
- echo $tag
- travis_wait make production
deploy:
  provider: releases
  token: $TOKEN
  file: releases/KnobControl-iOS-0.0.6.tar.gz
  cleanup: false
  draft: true