os: osx
osx_image: xcode9.3
language: swift
sudo: required
install:
- wget https://swift.org/builds/swift-5.0-branch/xcode/swift-5.0-DEVELOPMENT-SNAPSHOT-2019-03-24-a/swift-5.0-DEVELOPMENT-SNAPSHOT-2019-03-24-a-osx.pkg
- sudo installer -pkg swift-5.0-DEVELOPMENT-SNAPSHOT-2019-03-24-a-osx.pkg -target /
- export PATH="/Library/Developer/Toolchains/swift-5.0-DEVELOPMENT-SNAPSHOT-2019-03-24-a.xctoolchain/usr/bin:$PATH"
script:
- swift --version
- swift package update
- swift test
deploy:
  provider: releases
  api_key: $TOKEN
  file: releases/KnobControl-iOS-0.0.6.tar.gz
  skip_cleanup: true
  on:
    tags: true
