language: objective-c
os: osx
jobs:
  include:
  - osx_image: xcode11.3
    env: XCODE_VER=113
env:
  global:
    - tag=v0.0.7
before_script:
- brew tap tcnksm/ghr
- brew install ghr
script:
- travis_wait make production
before_deploy:
# Set up git user name and tag this commit
- export TRAVIS_TAG=$tag
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  token: $TOKEN
  file: releases/*
  skip_cleanup: true
  draft: true