language: objective-c
os: osx
osx_image: xcode11.3    
jobs:
  include:
  - env: SWIFT_VER=42
    script:
    - sh changeSwiftVersion.sh 4.2
    - travis_wait make production
  - env: SWIFT_VER=50
    script:
    - sh changeSwiftVersion.sh 5.0
    - travis_wait make production
  - env: SWIFT_VER=40
    script:
    - sh changeSwiftVersion.sh 4.0
    - travis_wait make production
env:
  global:
    - tag=0.0.11
before_deploy:
- export TRAVIS_TAG=$tag
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  token: $TOKEN
  file_glob: true
  file: releases/*
  skip_cleanup: true
  draft: true